# Generated by Django 4.2.30 on 2026-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=60)),
                ('to', models.CharField(max_length=60)),
                ('body', models.TextField()),
            ],
        ),
    ]
