# Generated by Django 4.2.30 on 2026-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='mail',
            field=models.TextField(),
        ),
    ]
