# Generated by Django 4.2.30 on 2026-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_utilisateur_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
